#!/bin/bash

set -e
ROOT="$(dirname "$0")"

# Check if it's a correct Java Home and a correct directory
if [[ -z "${JAVA_HOME}" || ! -d "${JAVA_HOME}" ]]; then
    export JAVA_HOME="$(readlink -f /usr/bin/java | sed "s:bin/java::" | sed "s:jre/::")"
fi
export JAVAC="${JAVA_HOME}/bin/javac"
export JAVA="${JAVA_HOME}/bin/java"

mkdir -p "${ROOT}/tmp/build/"
# The second argument is not fully quoted because we want to exploit shell
# expansion
${JAVAC} "${ROOT}"/builder/src/*.java -d "${ROOT}/tmp/build/"
cd "${ROOT}"
${JAVA} -cp tmp/build/ ZalBuilder "$@"
