#!/bin/bash

set -e
ROOT=$(dirname $0)

if [[ -z ${JAVA_HOME} ]]; then
    export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::" | sed "s:jre/::")
fi
export JAVAC=${JAVA_HOME}bin/javac
export JAVA=${JAVA_HOME}bin/java

mkdir -p ${ROOT}/tmp/build/
${JAVAC} ${ROOT}/build-src/*.java -d ${ROOT}/tmp/build/
cd ${ROOT}
${JAVA} -cp tmp/build/ ZalBuilder $@
