#!/usr/bin/env python2

import re
import os

#change directory in the script dir
current_path=os.path.realpath(__file__)
os.chdir( os.path.dirname(current_path) )

def writeTemplate( template_file, parameters, zimbra_version ):
  parameters = parameters.copy()

  if zimbra_version:
    versions = re.match("([0-9]+)\\.([0-9]+)\\.([0-9]+)",zimbra_version)
    parameters["MajorZimbraVersion"] = versions.group(1)
    parameters["MiddleZimbraVersion"] = versions.group(2)
    parameters["MinorZimbraVersion"] = versions.group(3)
    parameters["ZimbraVersion"] = zimbra_version

  text = open( template_file, "ro" ).read()
  for (key,value) in parameters.items():
    text = re.sub( "\\$\\{%s\\}"%key, value, text )
  print(text)

def join( list, prefix, suffix = "," ):
  joined=""
  for zimbra_version in list:
    joined += prefix+zimbra_version+suffix
  return joined[:-1]

ZimbraVersions=[
  "8.0.0", "8.0.1", "8.0.2", "8.0.3", "8.0.4",
  "8.0.5", "8.0.6", "8.0.7", "8.0.8", "8.0.9",
  "8.5.0", "8.5.1", "8.6.0", "8.7.0", "8.7.1",
  "8.7.2", "8.7.3", "8.7.4"
]

CommonZimbraVersions=[
  "8.0.0", "8.0.9",
  "8.6.0", "8.7.4"
]

MajorZimbraVersions=[
  "8.0.9",
  "8.5.1",
  "8.6.0",
  "8.7.4"
]

joined_zimbra_jar_versions  = join(ZimbraVersions, "zal-" )
joined_zimbra_test_versions = join(ZimbraVersions, "only-test-")
parallel_tests              = join(ZimbraVersions, '      <antcall target="only-test-', '-silent" />\n' )

joined_common_zimbra_jar_versions  = join(CommonZimbraVersions, "zal-" )
joined_common_zimbra_test_versions = join(CommonZimbraVersions, "only-test-")
common_parallel_tests              = join(CommonZimbraVersions, '      <antcall target="only-test-', '-silent" />\n' )

joined_zimbra_versions = join(ZimbraVersions, '')
joined_major_zimbra_versions = join(MajorZimbraVersions, '')

zal_version = file("../version").read().replace("\n","").replace("\r","")
version_pattern = re.compile("([0-9]+)\.([0-9]+)\.([0-9]+)")
version_matches = version_pattern.search(zal_version)

Parameters = {
  "VERSION": zal_version,
  "VERSION_MAJOR": version_matches.group(1),
  "VERSION_MINOR": version_matches.group(2),
  "VERSION_MICRO": version_matches.group(3),
  "DEBUG_ENABLED": "true",
  "DEBUG_LEVEL": "lines,vars,source",
  "COMPILER_ARGS": "-Xlint:none",
  "FIRST_ZIMBRA_VERSION": ZimbraVersions[0],
  "LAST_ZIMBRA_VERSION": ZimbraVersions[-1],
  "ZIMBRA_VERSIONS": joined_zimbra_versions,
  "MAJOR_ZIMBRA_VERSIONS": joined_major_zimbra_versions,
  "JOINED_ZIMBRA_JAR_VERSIONS": joined_zimbra_jar_versions,
  "JOINED_ZIMBRA_TEST_VERSIONS": joined_zimbra_test_versions,
  "JOINED_COMMON_ZIMBRA_JAR_VERSIONS": joined_common_zimbra_jar_versions,
  "JOINED_COMMON_ZIMBRA_TEST_VERSIONS": joined_common_zimbra_test_versions,
  "PARALLEL_TESTS": parallel_tests,
  "COMMON_PARALLEL_TESTS": common_parallel_tests
}

writeTemplate( "main_template_begin", Parameters, None )

for zimbra_version in ZimbraVersions:
  writeTemplate( "version_template",  Parameters, zimbra_version )

writeTemplate( "main_template_end",  Parameters, None )
